INSERT INTO config VALUES (1,2,3,36000,7,30,'["s"]','news',2,10,15,true,3000,30,'<strong>Fiat lux</strong>');
INSERT INTO "group" VALUES (1,'Admin','["sManageThreadP","sManageBoardP","sManageUsersP","sManageConfigP","sDeletePostsP","sManagePanelP","sManageBanP","sEditPostsP","sAdditionalMarkupP","sViewIPAndIDP","sViewModlogP","sChangeFileRatingP","sHellBanP","sShadowEditP"]');
INSERT INTO "user" VALUES (1,'admin','Admin','de41b7fb99201d8334c23c014db35ecd92df81bc','1');

INSERT INTO captcha_dict VALUES (1,'Десу','ru');
INSERT INTO captcha_dict VALUES (2,'Шинку','ru');
INSERT INTO captcha_dict VALUES (3,'Суигинто','ru');
INSERT INTO captcha_dict VALUES (4,'Боку','ru');
INSERT INTO captcha_dict VALUES (5,'Хина','ru');
INSERT INTO captcha_dict VALUES (6,'Кира','ru');
INSERT INTO captcha_dict VALUES (7,'Бара','ru');
INSERT INTO captcha_dict VALUES (8,'Кана','ru');
INSERT INTO captcha_dict VALUES (9,'Джун','ru');
INSERT INTO captcha_dict VALUES (10,'Нори','ru');
INSERT INTO captcha_dict VALUES (11,'Суисейсеки','ru');
INSERT INTO captcha_dict VALUES (12,'Соусейсеки','ru');
INSERT INTO captcha_dict VALUES (13,'Канария','ru');
INSERT INTO captcha_dict VALUES (14,'Киракишоу','ru');
INSERT INTO captcha_dict VALUES (15,'Барасуишоу','ru');

INSERT INTO captcha_dict VALUES (16,'Desu','en');
INSERT INTO captcha_dict VALUES (17,'Shinku','en');
INSERT INTO captcha_dict VALUES (18,'Suigintou','en');
INSERT INTO captcha_dict VALUES (19,'Boku','en');
INSERT INTO captcha_dict VALUES (20,'Hina','en');
INSERT INTO captcha_dict VALUES (21,'Kira','en');
INSERT INTO captcha_dict VALUES (22,'Bara','en');
INSERT INTO captcha_dict VALUES (23,'Kana','en');
INSERT INTO captcha_dict VALUES (24,'Jun','en');
INSERT INTO captcha_dict VALUES (25,'Nori','en');
INSERT INTO captcha_dict VALUES (26,'Suiseiseki','en');
INSERT INTO captcha_dict VALUES (27,'Souseiseki','en');
INSERT INTO captcha_dict VALUES (28,'Kanaria','en');
INSERT INTO captcha_dict VALUES (29,'Kirakishou','en');
INSERT INTO captcha_dict VALUES (30,'Barasuishou','en');
