Name: Name
Subject: Subject
SubmitBtn: Submit
Message: Message
Password: Password
File: File
Goback: Go back
Nobump: No bump

DeleteBtn: Delete
Open: Open
Pages: Pages:
Back: Back
Next: Next
Previous: Previous
ThreadHeaderReplyTo t@Int: Reply to #{show t} thread
PostsOmitted n@Int: #{show n} #{plural n "post" "posts"} omitted
NoThreads: No threads yet
Manage: Manage
Login: Login
Logout: Logout
Home: Home

NoImgOrText: File or image is required
UnknownError: Unknown error
BadFormData: Bad input
NoFormData: No input
TooLongMessage n@Int: Your message is too long. Max length is #{show n}
DeleteNoPosts: Didn't you forget to mark the posts you want to delete?
DeleteWrongPassword: Wrong password
TypeNotAllowed: This filetype isn't allowed
NoSuchThread: No such thread
NoSuchBoard: No such board
LockedThread: This thread is locked and can't be posted in

BoardId: ID
BoardName: Name
BoardDescription : Description
BoardBumpLimit   : Bump limit
BoardNumberFiles : Max number of files
BoardAllowedTypes: Allowed file types
BoardDefaultName : Default name
BoardMaxMsgLength: Max message length
BoardThumbSize : Thumb max size 
BoardThreadsPerPage: Threads per page        
BoardPreviewsPerThread: Previews per thread 
BoardHidden: Hidden
BoardThreadLimit: Max threads
BoardEnableCaptcha: Enable captcha
BoardCategory: Category
BoardCategories: Board categories (separate by comma)
HelpUpdateBoard: Leave ID field empty if you want to create a new board
UpdateBoardsBtn: Update boards
UpdateBoardsInvalidInput: Invalid input
DeleteAll: Delete all

WrongBoardId: Wrong board ID
BoardUpdated: Board successfully updated
BoardAdded: Board successfully added
BoardCleaned: Board successfully cleaned
BoardDeleted: Board successfully deleted
InvalidData: Invalid data

SupportedFileTypes: Supported file types are
MaxFileSize: Max file size allowed is

CleanBoard: Clean

LatestPosts: Latest posts
Boards: Boards
Bans: Bans

Ban: Ban
BanAdded: Ban successfully added
BanDeleted: Ban successfully deleted
BanIp: IP
BanReason: Reason
BanExpires: Expires
BanExpiresInHours: Expires (in hours)
BanBoard: Board
NeverExpires: Never
AllBoards: All boards
YouAreBanned reason@Text expires@Text: You are banned! Reason: "#{reason}". Your ban expires at #{expires}

Staff: Staff
Help: Help
Markup: Markup
Api: API
IfYouAreOp: If you are OP
IfYouAreNotOp: If you are not OP
IfPostBelongs: If this post belongs to you
IfPostDoesntBelong: If this post doesn't belong to you

SupportedLanguages: Supported languages for tag [code=<language>]

Role: Role
AddNewPerson: New person
StaffAdded: New person successufully added
StaffDeleted: Person successufully deleted
Account: Account
NewPassword: New password
PasswordChanged: Password successully changed
YouAreTheOnlyAdmin: You are the only Admin!

Captcha: Captcha
WrongCaptcha: Wrong captcha
ReloadPage: Reload page
TypeOnly: Type only 
ItalicChars: italic characters
UnderlineChars: underlined characters
BoldChars: bolded characters
RegularChars: regular characters
YouDontNeedCaptcha: You don't have to enter captcha

Config: Config
CaptchaLength: Captcha length
ACaptchaGuards: Guards of adaptive captcha
CaptchaTimeout: Captcha timeout
UpdateConfig: Update config
ConfigUpdated: Config successufly updated

PostingTooFast: You're posting too fast!
ReplyDelay: Reply delay
ThreadDelay: New thread delay
