Name: Name
Subject: Subject
SubmitBtn: Submit
Message: Message
Password: Password
File: File
Goback: Go back to
Nobump: No bump
ToThread: thread
ToBoard: board

DeleteBtn: Delete
Open: Open
Pages: Pages:
Back: Back
Next: Next
Previous: Previous
ThreadHeaderReplyTo t@Int: Reply to #{show t} thread
PostsOmitted n@Int: #{show n} #{plural n "post" "posts"} omitted.
ExpandThread: Expand thread.
ThreadIsExpanded: Thread is expanded.
TruncateThread: Truncate.
NoThreads: No threads yet
Manage: Manage
Login: Login
Logout: Logout
Home: Home

NoFileOrText: File or message is required
NoFile: File required
UnknownError: Unknown error
BadFormData: Bad input
NoFormData: No input
TooLongMessage n@Int: Your message is too long. Max length is #{show n}
DeleteNoPosts: Didn't you forget to mark the posts you want to delete?
DeleteWrongPassword: Wrong password
YouAreNotOp: Wrong OP password or session. You can't moderate this thread.
TypeNotAllowed: This filetype isn't allowed
NoSuchThread: No such thread
NoSuchBoard: No such board
LockedThread: This thread is locked and can't be posted in
PostSent: Post successfully sent

NewBoard: New board
BoardName: Name
BoardDescription : Description
BoardBumpLimit: Bump limit
BoardNumberFiles : Max number of files
BoardAllowedTypes: Allowed file types
BoardExtraRules: Extra rules
BoardDefaultName : Default name
BoardMaxMsgLength: Max message length
BoardThumbSize : Thumb max size 
BoardThreadsPerPage: Threads per page        
BoardPreviewsPerThread: Previews per thread 
BoardOpWithoutFile: Allow OPs without file
BoardHidden: Hidden
BoardThreadLimit: Max threads
BoardEnableCaptcha: Enable captcha
BoardCategory: Category
BoardCategories: Board categories (separate by comma)
BoardViewAccess: To view this board you must be a
BoardReplyAccess: To reply you must be a
BoardThreadAccess: To crate new thread you must be a
WontBeUpdatedIfNone: These settings won't be updated if their value is <None>
Optional: Optional
OpModeration: OP moderation
UpdateBoardsBtn: Update
UpdateBoardsInvalidInput: Invalid input
DeleteAll: Delete all

SeparateBy d@Text: Separate by '#{d}'

WrongBoardId: Wrong board ID
BoardsUpdated: Boards successfully updated
BoardAdded: Board successfully added
BoardCleaned: Board successfully cleaned
BoardDeleted: Board successfully deleted
InvalidData: Invalid data

SupportedFileTypes: Supported file types are
MaxFileSize: Max file size allowed is
ImgsWillBeThumbnailed s@Int: Images greater than #{show s}x#{show s} will be thumbnailed.
OpModerationIsEnabled: OP moderation is enabled on this board.

CleanBoard: Clean

LatestPosts: Latest posts
Boards: Boards
Bans: Bans

Ban: Ban
BanAdded: Ban successfully added
BanDeleted: Ban successfully deleted
BanIp: IP
BanReason: Reason
BanExpires: Expires
BanExpiresInHours: Expires (in hours)
BanBoard: Board
NeverExpires: Never
AllBoards: All boards
YouAreBanned reason@Text expires@Text: You are banned! Reason: "#{reason}". Your ban expires at #{expires}

Users: Users
Help: Help
Markup: Markup
IfYouAreOp: If you are OP
IfYouAreNotOp: If you are not OP
IfPostBelongs: If this post belongs to you
IfPostDoesntBelong: If this post doesn't belong to you

Api: API
ApiPostsAfter: All posts after {post id} in the thread
ApiLastPosts: Last {count} posts in the thread
ApiAllPosts: All posts in the thread
ApiDeletedPosts: All posts deleted by OP in the thread
ApiPost: One post
ApiParameters: Parameters
ApiBoardName: Board name (e.g., b, d, rm)
ApiThreadId: Displayed thread ID
ApiPostId: Displayed post ID
ApiCount: Number of posts

SupportedLanguages: Supported languages for tag [code=<language>]

Permissions: Permissions
GroupAdded: Group added
GroupAdd: Add group
ManageThread:Manage Thread
ManageBoard :Manage Board
ManageUsers :Manage Users
ManageConfig:Manage Config
DeletePosts :Delete Posts
ManagePanel :Manage Panel
ManageBan   :Manage Ban

Group: Group
Groups: Groups
AddNewUser: New user
UsersAdded: New user successufully added
UsersDeleted: User successufully deleted
Account: Account
NewPassword: New password
PasswordChanged: Password successully changed
YouAreTheOnlyWhoCanManageUsers: You are the only who can manage users!

Captcha: Captcha
WrongCaptcha: Wrong captcha
ReloadPage: Reload page
TypeOnly: Type only 
ItalicChars: italic characters
UnderlineChars: underlined characters
BoldChars: bolded characters
RegularChars: regular (not bolded, not italic, not underlined) characters
YouDontNeedCaptcha: You don't have to enter captcha

Config: Config
CaptchaLength: Captcha length
ACaptchaGuards: Guards of adaptive captcha
CaptchaTimeout: Captcha timeout
ShowNews: How many news show
NewsBoard: Board for news
UpdateConfig: Update config
ConfigUpdated: Config successufly updated

PostingTooFast: You're posting too fast!
ReplyDelay: Reply delay
ThreadDelay: New thread delay

GetNewPosts: Get new posts
NoNewPosts: No new posts

Replies: Replies:
CloseAllPopup: Close all popups
CloseOnePopup: Close one

NewThread: New thread
ClosePostForm: Close form
Reply: Reply
ReplyToThread: Reply to thread №

ThreadNotExist: This thread doesn't exist anymore
NoPostsAnymore: Ooops, no posts in this thread!
Loading: Loading...

Management: Management
BanManagement: Ban management
BoardManagement: Board management

Enable: Enabled
Disable: Disabled

XForUnlim x@Text: #{x} for unlimited
PostFormBumpLimit b@Int: Bump limit is #{unlimitedBump b "unlimited"}

News: News

DeletedPosts: Deleted posts
DeletedPostsIn z@Int: Deleted posts in thread №#{show z}
ShowDeletedPosts: Show deleted posts

BanPoster: Ban poster
StickThread: Stick/unstick
LockThread: Lock/unlock
Autosage: Autosage
