Name: Имя
Subject: Тема
SubmitBtn: Отправить
Message: Текст
Password: Пароль
File: Файл
Goback: Перейти к
Nobump: Не бампать

DeleteBtn: Удалить
Open: Открыть
Pages: Страницы:
Back: Назад
Next: Вперед
Previous: Назад
ThreadHeaderReplyTo t@Int: Ответ в тред №#{show t}
PostsOmitted n@Int: #{show n} #{plural n "пост" "постов"} пропущено
NoThreads: Нет тредов
Manage: Управление
Login: Войти
Logout: Выйти
Home: Домой

NoImgOrText: Необходимо ввести текст или прикрепить файл
UnknownError: Неизвестная ошибка
BadFormData: Введены неверные данные
NoFormData: Ничего не введено
TooLongMessage n@Int: Сообщение слишком длинное. Максимальная длина #{show n}
DeleteNoPosts: Не отмечено постов к удалению
DeleteWrongPassword: Неправильный пароль
TypeNotAllowed: Данный тип файла не разрешен к загрузк
NoSuchThread: Нет такого треда
NoSuchBoard: Нет такой борды
LockedThread: Тред закрыт

BoardId: ID
BoardName: Имя
BoardDescription : Описание
BoardBumpLimit   : Бамп-лимит
BoardNumberFiles : Макс. число файлов
BoardAllowedTypes: Типы файлов
BoardDefaultName : Стандартное имя
BoardMaxMsgLength: Макс. длина текста
BoardThumbSize : Размер превью
BoardThreadsPerPage: Тредов на странице
BoardPreviewsPerThread: Превью-постов
BoardHidden: Скрытая
BoardThreadLimit: Максимум тредов
BoardEnableCaptcha: Капча
HelpUpdateBoard: Оставьте ID пустым для создания новой борды
UpdateBoardsBtn: Обновить борды
UpdateBoardsInvalidInput: Неверный тип данных
DeleteAll: Удалить все

WrongBoardId: Неправильное ID борды
BoardUpdated: Борда обновлена
BoardAdded: Борда добавлена
BoardCleaned: Борда очищена от всех постов
BoardDeleted: Борда удалена
InvalidData: Неверные данные

SupportedFileTypes: Поддерживаемые типы файлов:
MaxFileSize: Маскимальный размер файла:

CleanBoard: Очистить

LatestPosts: Последние посты
Boards: Борды
Bans: Баны

Ban: Бан
BanAdded: Бан добавлен
BanDeleted: Бан удален
BanIp: IP
BanReason: Причина
BanExpires: Истекает
BanExpiresInHours: Истекает через * часов
BanBoard: На борде
NeverExpires: Никогда
AllBoards: Все борды
YouAreBanned reason@Text expires@Text: Вы забанены! Причина: "#{reason}". Бан истекает #{expires}

Staff: Персонал
Help: Помощь
Markup: Разметка

SupportedLanguages: Поддерживаемые языки для тега [code=<язык>]

Role: Роль
AddNewPerson: Новый аккаунт
StaffAdded: Аккаунт добавлен
StaffDeleted: Аккаунт удален
Account: Мой аккаунт
NewPassword: Новый пароль
PasswordChanged: Пароль изменен
YouAreTheOnlyAdmin: Вы единственный админ!

Captcha: Капча
WrongCaptcha: Неверная капча
ReloadPage: Перезагрузить страницу
TypeOnly: Вводите только
ItalicChars: курсивные символы
UnderlineChars: подчеркнутые символы
BoldChars: жирные символы
RegularChars: обычные символы
YouDontNeedCaptcha: Вам не нужно вводить капчу

Config: Настройки
CaptchaLength: Длина капчи
ACaptchaGuards: Капч нужно ввести для постинга без капчи
CaptchaTimeout: Таймаут капчи
UpdateConfig: Обновить настройки
ConfigUpdated: Настройки обновлены

PostingTooFast: Вы постите слишком часто. Упырьте мел.
ReplyDelay: Задержка перед ответом в тред
ThreadDelay: Задержка перед созданием нового треда
