#!/bin/bash
db='../Monaba.sqlite3'
password='passwd'

sqlite3 $db .dump > dump.sqlite
echo "make sqlite dump"

sed \
-e '/PRAGMA.*;/ d' \
-e '/BEGIN TRANSACTION.*/ d' \
-e '/COMMIT;/ d' \
-e '/.*sqlite_sequence.*;/d' \
-e 's/"/`/g' \
-e 's/CREATE TABLE \(`\w\+`\)/DROP TABLE IF EXISTS \1;\nCREATE TABLE \1/' \
-e 's/\(CREATE TABLE.*\)\(PRIMARY KEY\) \(AUTOINCREMENT\)\(.*\)\();\)/\1AUTO_INCREMENT\4, PRIMARY KEY(id)\5/' \
-e "s/'t'/1/g" \
-e "s/'f'/0/g" \
dump.sqlite > dump.sql
rm dump.sqlite
echo "convert sqlite to mysql"

perl -ni -e 'print unless /CREATE|DROP|(INSERT INTO `(person|history|captcha)`)/' dump.sql
echo "remove junk"

perl -pi -e 's/\[`(s|u)/\[\\"$1/g; s/`,`s/\\",\\"s/g; s/`\]/\\"\]/g;' dump.sql
echo "fix lists"

perl -pi -e 's/\.\d+ UTC//g' dump.sql
echo "fix time"

M=$(mysql -u root -p$password -e 'drop database Monaba; \
source init-database.sql; \
source dump.sql;')
echo $M
rm dump.sql

echo "done"
